# Generated by Django 5.1.7 on 2026-04-18 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60, unique=True)),
                ('current_json', models.TextField()),
                ('forecast_json', models.TextField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Cache',
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('alert_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Log',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Admin')], default='farmer', max_length=10)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, default='Mumbai', max_length=60)),
                ('farm_size', models.FloatField(blank=True, help_text='Acres', null=True)),
                ('irrigation', models.CharField(blank=True, choices=[('rainfed', 'Rain-fed'), ('borewell', 'Borewell'), ('canal', 'Canal'), ('drip', 'Drip / Sprinkler')], max_length=20)),
                ('soil_type', models.CharField(blank=True, choices=[('black', 'Black / Cotton'), ('red', 'Red / Laterite'), ('alluvial', 'Alluvial / Sandy loam'), ('loamy', 'Loamy / Mixed')], max_length=20)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('crop_stage', models.CharField(blank=True, choices=[('Sowing', 'Sowing'), ('Vegetative', 'Vegetative'), ('Flowering', 'Flowering'), ('Harvest', 'Harvest')], max_length=20)),
                ('crops_json', models.TextField(blank=True, default='[]', help_text='JSON list of crop names e.g. ["Wheat","Rice"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
            },
        ),
    ]
